require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Signspot::ThreadsController do

  # This should return the minimal set of attributes required to create a valid
  # Signspot::Thread. As you add validations to Signspot::Thread, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Signspot::ThreadsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all signspot_threads as @signspot_threads" do
      thread = Signspot::Thread.create! valid_attributes
      get :index, {}, valid_session
      assigns(:signspot_threads).should eq([thread])
    end
  end

  describe "GET show" do
    it "assigns the requested thread as @thread" do
      thread = Signspot::Thread.create! valid_attributes
      get :show, {:id => thread.to_param}, valid_session
      assigns(:thread).should eq(thread)
    end
  end

  describe "GET new" do
    it "assigns a new thread as @thread" do
      get :new, {}, valid_session
      assigns(:thread).should be_a_new(Signspot::Thread)
    end
  end

  describe "GET edit" do
    it "assigns the requested thread as @thread" do
      thread = Signspot::Thread.create! valid_attributes
      get :edit, {:id => thread.to_param}, valid_session
      assigns(:thread).should eq(thread)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Signspot::Thread" do
        expect {
          post :create, {:thread => valid_attributes}, valid_session
        }.to change(Signspot::Thread, :count).by(1)
      end

      it "assigns a newly created thread as @thread" do
        post :create, {:thread => valid_attributes}, valid_session
        assigns(:thread).should be_a(Signspot::Thread)
        assigns(:thread).should be_persisted
      end

      it "redirects to the created thread" do
        post :create, {:thread => valid_attributes}, valid_session
        response.should redirect_to(Signspot::Thread.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved thread as @thread" do
        # Trigger the behavior that occurs when invalid params are submitted
        Signspot::Thread.any_instance.stub(:save).and_return(false)
        post :create, {:thread => {}}, valid_session
        assigns(:thread).should be_a_new(Signspot::Thread)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Signspot::Thread.any_instance.stub(:save).and_return(false)
        post :create, {:thread => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested thread" do
        thread = Signspot::Thread.create! valid_attributes
        # Assuming there are no other signspot_threads in the database, this
        # specifies that the Signspot::Thread created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Signspot::Thread.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => thread.to_param, :thread => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested thread as @thread" do
        thread = Signspot::Thread.create! valid_attributes
        put :update, {:id => thread.to_param, :thread => valid_attributes}, valid_session
        assigns(:thread).should eq(thread)
      end

      it "redirects to the thread" do
        thread = Signspot::Thread.create! valid_attributes
        put :update, {:id => thread.to_param, :thread => valid_attributes}, valid_session
        response.should redirect_to(thread)
      end
    end

    describe "with invalid params" do
      it "assigns the thread as @thread" do
        thread = Signspot::Thread.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Signspot::Thread.any_instance.stub(:save).and_return(false)
        put :update, {:id => thread.to_param, :thread => {}}, valid_session
        assigns(:thread).should eq(thread)
      end

      it "re-renders the 'edit' template" do
        thread = Signspot::Thread.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Signspot::Thread.any_instance.stub(:save).and_return(false)
        put :update, {:id => thread.to_param, :thread => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested thread" do
      thread = Signspot::Thread.create! valid_attributes
      expect {
        delete :destroy, {:id => thread.to_param}, valid_session
      }.to change(Signspot::Thread, :count).by(-1)
    end

    it "redirects to the signspot_threads list" do
      thread = Signspot::Thread.create! valid_attributes
      delete :destroy, {:id => thread.to_param}, valid_session
      response.should redirect_to(signspot_threads_url)
    end
  end

end
